// Generated by gencpp from file py_tutorials/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PY_TUTORIALS_MESSAGE_ADDTWOINTS_H
#define PY_TUTORIALS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <py_tutorials/AddTwoIntsRequest.h>
#include <py_tutorials/AddTwoIntsResponse.h>


namespace py_tutorials
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace py_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::py_tutorials::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::py_tutorials::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::py_tutorials::AddTwoInts > {
  static const char* value()
  {
    return "py_tutorials/AddTwoInts";
  }

  static const char* value(const ::py_tutorials::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::py_tutorials::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::py_tutorials::AddTwoInts > 
template<>
struct MD5Sum< ::py_tutorials::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::py_tutorials::AddTwoInts >::value();
  }
  static const char* value(const ::py_tutorials::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::py_tutorials::AddTwoIntsRequest> should match 
// service_traits::DataType< ::py_tutorials::AddTwoInts > 
template<>
struct DataType< ::py_tutorials::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::py_tutorials::AddTwoInts >::value();
  }
  static const char* value(const ::py_tutorials::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::py_tutorials::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::py_tutorials::AddTwoInts > 
template<>
struct MD5Sum< ::py_tutorials::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::py_tutorials::AddTwoInts >::value();
  }
  static const char* value(const ::py_tutorials::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::py_tutorials::AddTwoIntsResponse> should match 
// service_traits::DataType< ::py_tutorials::AddTwoInts > 
template<>
struct DataType< ::py_tutorials::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::py_tutorials::AddTwoInts >::value();
  }
  static const char* value(const ::py_tutorials::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PY_TUTORIALS_MESSAGE_ADDTWOINTS_H
